name: Build Website

on:
  push:
    branches: [main]
    paths:
      - "website/**"
      - ".github/workflows/build-website.yml"
  pull_request:
    paths:
      - "website/**"
      - ".github/workflows/build-website.yml"

jobs:
  build:
    name: Typecheck, lint, and build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: website/package-lock.json

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install dependencies
        run: npm ci

      - name: Audit npm lockfile
        run: npm audit --omit=dev

      - name: Check lint and formatting
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build
