#!/usr/bin/env python3
"""Regenerate the skill inventory in README.md from index.yaml.

Everything between the BEGIN/END markers in README.md is rewritten: the pack
table and, per pack, every skill with the first sentence of its summary. Pack
descriptions come from each group's ``.robomotion/skill.yaml`` ``summary``, so
edit them there, not in the README.

Usage::

    python3 build-index.py && python3 build-readme.py    # rewrite README.md
    python3 build-readme.py --check                      # exit 1 if README.md is stale
"""

from __future__ import annotations

import os
import re
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install pyyaml")

BEGIN = "<!-- BEGIN GENERATED by build-readme.py; edit .robomotion/skill.yaml, not this -->"
END = "<!-- END GENERATED -->"

# Display order; a category not listed here sorts after these.
CATEGORIES = ["Engineering", "Cloud", "DevOps", "Database", "Design", "Marketing",
              "Media", "Productivity", "Automation", "Research", "General"]
MAX_DESC = 160


def repo_name(url: str) -> str:
    m = re.match(r"https://github\.com/([^/]+/[^/]+)", url or "")
    return m.group(1) if m else url


def cell(text: str) -> str:
    """One line of text, safe inside a table cell. Outside `code` spans, <, >
    and * are escaped so they print as typed; inside them they already do."""
    text = re.sub(r"\s+", " ", text or "").strip()
    if text.count("`") % 2:
        text = text.replace("`", "")
    parts = text.split("`")
    for i in range(0, len(parts), 2):
        parts[i] = parts[i].replace("<", "&lt;").replace(">", "&gt;").replace("*", "\\*")
    return "`".join(parts).replace("|", "\\|")


# A full stop after one of these does not end the sentence.
ABBREV = re.compile(r"(?:\be\.g|\bi\.e|\betc|\bvs|\bv\d+(?:\.\d+)*)\.$", re.I)


def first_sentence(text: str) -> str:
    text = re.sub(r"\s+", " ", text or "").strip()
    for m in re.finditer(r"[.!?](?=\s|$)", text):
        if not ABBREV.search(text[:m.end()]):
            text = text[:m.end()]
            break
    if len(text) > MAX_DESC:
        text = text[:MAX_DESC].rsplit(" ", 1)[0].rstrip(",;:—-") + "…"
    return cell(text)


def render(index: dict) -> str:
    groups = index["groups"]
    order = {c: i for i, c in enumerate(CATEGORIES)}
    groups = sorted(groups, key=lambda g: (order.get(g.get("category"), len(order)),
                                           g.get("category") or "", -len(g["skills"]), g["path"]))
    total = sum(len(g["skills"]) for g in groups)

    out = ["## Packs", "", f"**{len(groups)} packs, {total:,} skills.**", "",
           "| Pack | Category | Skills | Source | What it does |",
           "|---|---|---:|---|---|"]
    for g in groups:
        src = g.get("source_url", "")
        source = "Robomotion" if "robomotionio/" in src else f"[{repo_name(src)}]({src})"
        out.append(f"| [`{g['path']}`]({g['path']}/) | {g.get('category', '')} | {len(g['skills'])} "
                   f"| {source} | {cell(g.get('summary'))} |")

    out += ["", "## All skills", "",
            "Every skill, by pack. Click a pack to open its list; a skill's name links to its folder.", ""]
    category = None
    for g in groups:
        if g.get("category") != category:
            category = g.get("category")
            out += [f"### {category}", ""]
        n = len(g["skills"])
        out += ["<details>",
                f"<summary><b>{g['path']}</b> — {n} skill{'s' if n != 1 else ''} "
                f"from {cell(g.get('author'))}</summary>", "",
                "| Skill | What it does |", "|---|---|"]
        for s in sorted(g["skills"], key=lambda s: s["name"]):
            out.append(f"| [`{s['name']}`]({s['path']}/) | {first_sentence(s.get('summary'))} |")
        out += ["", "</details>", ""]
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    root = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(root, "index.yaml")) as fh:
        index = yaml.safe_load(fh)
    path = os.path.join(root, "README.md")
    with open(path) as fh:
        readme = fh.read()
    if BEGIN not in readme or END not in readme:
        sys.exit(f"README.md has no generated section; add these two lines where it belongs:\n{BEGIN}\n{END}")
    head, rest = readme.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    new = f"{head}{BEGIN}\n{render(index)}{END}{tail}"

    if "--check" in sys.argv[1:]:
        if new != readme:
            sys.stderr.write("README.md is stale — run `python3 build-readme.py` and commit.\n")
            return 1
        print("README.md up to date")
        return 0
    with open(path, "w") as fh:
        fh.write(new)
    print("wrote README.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
